export enum UserPermission {
    READ = 'r',
    WRITE = 'w',
}
const DEFAULT_TOKEN_EXPIRE_TIME = 14 * 24 * 60 * 60 * 1000; // 14 days
const DEFAULT_USER_PERMISSION = UserPermission.READ;
//
const INVALID_USER_ID = '';
const INVALID_USER_NAME = '';
const INVALID_USER_PASSWORD_HASH = '';
const INVALID_USER_SALT = '';
const INVALID_USER_ACCOUNT_EXPIRE_TIME = new Date(0);
const INVALID_USER_TOKEN_EXPIRE_TIME = new Date(0);
const INVALID_USER_LAST_LOGIN_TIME = new Date(0);
const INVALID_USER_LOGIN_TOKEN = '';
//
type contect_schema_Passport = {
    provider:string;
    id:string;
    displayName:string;
    name:{
        familyName:string;
        givenName:string;
        middleName:string;
    },
    emails: string[]
}
// ??
/**
 * User profile for passport
 *  provider {String}
    The provider with which the user authenticated (facebook, twitter, etc.).
    id {String}
    A unique identifier for the user, as generated by the service provider.
    displayName {String}
    The name of this user, suitable for display.
    name {Object}
    familyName {String}
    The family name of this user, or "last name" in most Western languages.
    givenName {String}
    The given name of this user, or "first name" in most Western languages.
    middleName {String}
    The middle name of this user.
    emails {Array} [n]
    value {String}
    The actual email address.
    type {String}
    The type of email address (home, work, etc.).
    photos {Array} [n]
    value {String}
    The URL of the image.
 */
// 
/**  Class for user */
export class User {
    #id: string;
    #username: string;
    #hashed_password: string;
    #salt: string;
    #isPermanent: boolean;
    #accountExpireTime: Date;
    #tokenExpireTime: Date;
    #lastLoginTime: Date;
    #loginToken: string;
    #permission: UserPermission;
    constructor(
        id: string,
        username: string,
        hashed_password: string,
        salt: string,
        accountExpireTime: Date,
        tokenExpireTime: Date,
        lastLoginTime: Date,
        loginToken: string,
        permission: UserPermission
    ) {
        this.#id = id;
        this.#username = username;
        this.#hashed_password = hashed_password;
        this.#salt = salt;
        this.#isPermanent = accountExpireTime === null;
        this.#lastLoginTime = lastLoginTime;
        this.#loginToken = loginToken;
        this.#accountExpireTime = accountExpireTime;
        this.#permission = permission;
        this.#tokenExpireTime = tokenExpireTime;
    }
    //
    get id() {
        return this.#id;
    }
    get name() {
        return this.#username;
    }
    get expireTime() {
        return this.#tokenExpireTime;
    }
    get isPermanent() {
        return this.#isPermanent;
    }
    get accountExpireTime() {
        return this.#accountExpireTime;
    }
    get salt() {
        return this.#salt;
    }
    get hashed_password() {
        return this.#hashed_password;
    }
}
export class UserBuilder {
    #id: string;
    #name: string;
    #hashed_password: string;
    #salt: string;
    #isPermanent: boolean;
    #accountExpireTime: Date;
    #tokenExpireTime: Date;
    #lastLoginTime: Date;
    #loginToken: string;
    #permission: UserPermission;
    constructor() {
        this.#id = INVALID_USER_ID;
        this.#name = INVALID_USER_NAME;
        this.#hashed_password = INVALID_USER_PASSWORD_HASH;
        this.#salt = INVALID_USER_SALT;
        this.#isPermanent = false;
        this.#accountExpireTime = INVALID_USER_ACCOUNT_EXPIRE_TIME;
        this.#tokenExpireTime = INVALID_USER_TOKEN_EXPIRE_TIME;
        this.#lastLoginTime = INVALID_USER_LAST_LOGIN_TIME;
        this.#loginToken = INVALID_USER_LOGIN_TOKEN;
        this.#permission = DEFAULT_USER_PERMISSION;
    }
    build() {
        if (this.assertValid()) {
            return new User(
                this.#id,
                this.#name,
                this.#hashed_password,
                this.#salt,
                this.#accountExpireTime as Date,
                this.#tokenExpireTime as Date,
                this.#lastLoginTime as Date,
                this.#loginToken,
                this.#permission
            );
        } else {
            return null;
        }
    }
    assertValid(): boolean {
        return (
            this.#id !== INVALID_USER_ID &&
            this.#name !== INVALID_USER_NAME &&
            this.#hashed_password !== INVALID_USER_PASSWORD_HASH &&
            this.#salt !== INVALID_USER_SALT &&
            this.#accountExpireTime !== INVALID_USER_ACCOUNT_EXPIRE_TIME &&
            this.#tokenExpireTime !== INVALID_USER_TOKEN_EXPIRE_TIME &&
            this.#lastLoginTime !== INVALID_USER_LAST_LOGIN_TIME &&
            this.#loginToken !== INVALID_USER_LOGIN_TOKEN
        );
    }
    setId(id: string) {
        this.#id = id;
        return this;
    }
    setName(name: string) {
        this.#name = name;
        return this;
    }
    setHash(hashed_password: string, salt: string) {
        this.#hashed_password = hashed_password;
        this.#salt = salt;
        return this;
    }
    setPermanent(isPermanent: boolean) {
        this.#isPermanent = isPermanent;
        return this;
    }
    setAccountExpireTime(accountExpireTime: Date) {
        this.#accountExpireTime = accountExpireTime;
        return this;
    }
    setTokenExpireTime(tokenExpireTime: Date) {
        this.#tokenExpireTime = tokenExpireTime;
        return this;
    }
    setLastLoginTime(lastLoginTime: Date) {
        this.#lastLoginTime = lastLoginTime;
        return this;
    }
    setLoginToken(loginToken: string) {
        this.#loginToken = loginToken;
        return this;
    }
    setPermission(permission: UserPermission) {
        this.#permission = permission;
        return this;
    }
}
